version: "3"

services:
  inventory-api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: env/dev
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - GREMLIN_ENDPOINT
      - GREMLIN_AUTH_MODE
    extra_hosts:
      - "${DOCKER_EXTRA_HOST}"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      gremlin-server:
        condition: service_healthy
    entrypoint: ["python"]
    command: ["graph_asset_inventory_api/app.py"]

  graph-notebook:
    image: adevinta/graph-notebook-docker:v1.0.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
    extra_hosts:
      - "${DOCKER_EXTRA_HOST}"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    depends_on:
      gremlin-server:
        condition: service_healthy

  gremlin-server:
    image: tinkerpop/gremlin-server:3.5.0
    entrypoint: /opt/gremlin-server/bin/gremlin-server.sh
    command: conf/gremlin-server.yaml
    expose:
      - "8182"
    volumes:
      - ./gremlin-server/conf:/opt/gremlin-server/conf:ro
    healthcheck:
      test: ["CMD", "nc", "-z", "gremlin-server:8182"]
      interval: 5s
      timeout: 10s
      retries: 6
