FROM python:3.9.6-alpine

# Install system dependencies.
RUN apk add gcc musl-dev

# Set workdir to /app.
WORKDIR /app

# Install Python requirements.
COPY requirements/requirements.txt requirements/requirements-dev.txt .
RUN pip install -r requirements.txt -r requirements-dev.txt && \
	rm -f requirements.txt requirements-dev.txt

# Set Python's class path
ENV PYTHONPATH=/app
