# Builder stage for getting amanzon-neptune-tools.
FROM python:3.9.12-alpine3.15 as builder

RUN apk add git

RUN git clone --depth 1 --branch amazon-neptune-tools-1.7 \
	https://github.com/awslabs/amazon-neptune-tools /amazon-neptune-tools


# Stage for the graph-asset-inventory-api dev image.
FROM python:3.9.12-alpine3.15

RUN apk add gcc g++ musl-dev libffi-dev

COPY requirements/requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt && rm -f /tmp/requirements-dev.txt

RUN mkdir -p /app
WORKDIR /app

RUN mkdir -p /deps
COPY --from=builder \
	/amazon-neptune-tools/neptune-python-utils/neptune_python_utils \
	/deps/neptune_python_utils

ENV PYTHONPATH="/app:/deps"
