version: "3"

services:
  inventory-api-lint:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: env/dev
    volumes:
      - .:/app
    entrypoint: ["/bin/sh"]
    command: ["-c", " \
      echo 'Running flake8...' && flake8 ${LINTER_PATHS} && \
      echo 'Running pylint...' && pylint ${LINTER_PATHS} \
    "]
