openapi: 3.0.3
info:
  title: graph-asset-inventory-api
  description: Security Graph. Asset Inventory API.
  version: 1.0.0

paths:
  /v1/teams:
    get:
      operationId: graph_asset_inventory_api.api.teams.get_teams
      summary: Returns the list of teams.
      tags:
        - Teams
        - v1
      parameters:
        - in: query
          name: page
          description: Index of the page.
          schema:
            type: integer
          required: false
        - in: query
          name: size
          description: Number of results per page.
          schema:
            type: integer
          required: false
        - in: query
          name: team_identifier
          description: Identifier of the team.
          schema:
            type: string
          required: false
      responses:
        '200':
          description: A JSON array of teams.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamResp'

    post:
      operationId: graph_asset_inventory_api.api.teams.post_teams
      summary: Creates a team.
      tags:
        - Teams
        - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamReq'
      responses:
        '201':
          description: A JSON object with the created team.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamResp'
        '409':
          description: The team already exists.

  /v1/teams/{id}:
    parameters:
      - in: path
        name: id
        description: ID of the team.
        schema:
          type: string
          format: uuid
        required: true

    get:
      operationId: graph_asset_inventory_api.api.teams.get_teams_id
      summary: Returns a team.
      tags:
        - Teams
        - v1
      responses:
        '200':
          description: A JSON object with the team.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamResp'
        '404':
          description: The team was not found.

    put:
      operationId: graph_asset_inventory_api.api.teams.put_teams_id
      summary: Updates a team.
      tags:
        - Teams
        - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamReq'
      responses:
        '200':
          description: A JSON object with the updated team.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamResp'
        '404':
          description: The team was not found.

    delete:
      operationId: graph_asset_inventory_api.api.teams.delete_teams_id
      summary: Deletes a team.
      tags:
        - Teams
        - v1
      responses:
        '204':
          description: The team has been deleted successfully.
        '404':
          description: The team was not found.

  /v1/assets:
    get:
      operationId: graph_asset_inventory_api.api.assets.get_assets
      summary: Returns the list of assets.
      tags:
        - Assets
        - v1
      parameters:
        - in: query
          name: page
          description: Index of the page.
          schema:
            type: integer
          required: false
        - in: query
          name: size
          description: Number of results per page.
          schema:
            type: integer
          required: false
        - in: query
          name: asset_type
          description: Type of the assets.
          schema:
            type: string
          required: false
        - in: query
          name: asset_identifier
          description: Identifier of the assets.
          schema:
            type: string
          required: false
      responses:
        '200':
          description: A JSON array of assets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssetResp'

    post:
      operationId: graph_asset_inventory_api.api.assets.post_assets
      summary: Creates an asset.
      tags:
        - Assets
        - v1
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/AssetReq'
                - type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
      responses:
        '201':
          description: A JSON object with the created asset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetResp'
        '409':
          description: The asset already exists.

  /v1/assets/{id}:
    parameters:
      - in: path
        name: id
        description: ID of the asset.
        schema:
          type: string
          format: uuid
        required: true

    get:
      operationId: graph_asset_inventory_api.api.assets.get_assets_id
      summary: Returns an asset.
      tags:
        - Assets
        - v1
      responses:
        '200':
          description: A JSON object with the asset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetResp'
        '404':
          description: The asset was not found.

    put:
      operationId: graph_asset_inventory_api.api.assets.put_assets_id
      summary: Updates an asset.
      tags:
        - Assets
        - v1
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/AssetReq'
                - type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
      responses:
        '200':
          description: A JSON object with the updated asset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetResp'
        '404':
          description: The asset was not found.

    delete:
      operationId: graph_asset_inventory_api.api.assets.delete_assets_id
      summary: Deletes an asset.
      tags:
        - Assets
        - v1
      responses:
        '204':
          description: The asset has been deleted successfully.
        '404':
          description: The asset was not found.

  /v1/assets/{id}/parents:
    parameters:
      - in: path
        name: id
        description: ID of the asset.
        schema:
          type: string
          format: uuid
        required: true

    get:
      operationId: graph_asset_inventory_api.api.parents.get_assets_id_parents
      summary: Returns the list of child-of relationships of an asset.
      tags:
        - Assets
        - Parents
        - v1
      parameters:
        - in: query
          name: page
          description: Index of the page.
          schema:
            type: integer
          required: false
        - in: query
          name: size
          description: Number of results per page.
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: A JSON array of relationships.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ParentOfResp'
        '404':
          description: The asset was not found.

  /v1/assets/{child_id}/parents/{parent_id}:
    parameters:
      - in: path
        name: child_id
        description: ID of the child asset.
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: parent_id
        description: ID of the parent asset.
        schema:
          type: string
          format: uuid
        required: true

    put:
      operationId: graph_asset_inventory_api.api.parents.put_assets_child_id_parents_parent_id
      summary: Adds a parent to an asset or updates an existing relationship.
      tags:
        - Assets
        - Parents
        - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParentOfReq'
      responses:
        '200':
          description: A JSON object with the updated relationship.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParentOfResp'
        '201':
          description: A JSON object with the created relationship.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParentOfResp'
        '404':
          description: At least one of the assets do not exist.

    delete:
      operationId: graph_asset_inventory_api.api.parents.delete_assets_child_id_parents_parent_id
      summary: Deletes a child-of relationship.
      tags:
        - Assets
        - Parents
        - v1
      responses:
        '204':
          description: The relationship has been deleted successfully.
        '404':
          description: At least one of the assets or the relationship were not found.

  /v1/assets/{id}/owners:
    parameters:
      - in: path
        name: id
        description: ID of the asset.
        schema:
          type: string
          format: uuid
        required: true

    get:
      operationId: graph_asset_inventory_api.api.owners.get_assets_id_owners
      summary: Returns the list of owned-by relationships of an asset.
      tags:
        - Assets
        - Teams
        - Owners
        - v1
      parameters:
        - in: query
          name: page
          description: Index of the page.
          schema:
            type: integer
          required: false
        - in: query
          name: size
          description: Number of results per page.
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: A JSON array of relationships.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OwnsResp'

  /v1/assets/{asset_id}/owners/{team_id}:
    parameters:
      - in: path
        name: asset_id
        description: ID of the asset.
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: team_id
        description: ID of the team.
        schema:
          type: string
          format: uuid
        required: true

    put:
      operationId: graph_asset_inventory_api.api.owners.put_assets_asset_id_owners_team_id
      summary: Adds an owner to an asset or updates and existing relationship.
      tags:
        - Assets
        - Teams
        - Owners
        - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OwnsReq'
      responses:
        '200':
          description: A JSON object with the updated relationship.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnsResp'
        '201':
          description: A JSON object with the created relationship.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OwnsResp'
        '404':
          description: The asset or the team do not exist.

    delete:
      operationId: graph_asset_inventory_api.api.owners.delete_assets_asset_id_owners_team_id
      summary: Deletes an owned-by relationship.
      tags:
        - Assets
        - Teams
        - Owners
        - v1
      responses:
        '204':
          description: The relationship has been deleted successfully.
        '404':
          description: The asset, the team or the relationship were not found.

  /v1/assets/bulk:
    post:
      operationId: graph_asset_inventory_api.api.assets_bulk.post_assets_bulk
      summary: Creates multiple assets and their relationships.
      tags:
        - Assets
        - Parents
        - Bulk
        - v1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                assets:
                  type: array
                  items:
                    allOf:
                      - $ref: '#/components/schemas/AssetReq'
                      - type: object
                        properties:
                          parents:
                            type: array
                            items:
                              allOf:
                                - $ref: '#/components/schemas/AssetTupleID'
                                - $ref: '#/components/schemas/ParentOfReq'
              required:
                - assets
      responses:
        '204':
          description: The assets and their relationships were successfully created.
        '404':
          description: A parent asset was not found.

components:
  schemas:
    # Team
    TeamReq:
      type: object
      properties:
        identifier:
          type: string
        name:
          type: string
      required:
        - identifier
        - name

    TeamResp:
      type: object
      properties:
        id:
          type: integer
        identifier:
          type: string
        name:
          type: string
      required:
        - id
        - identifier
        - name

    # Asset
    AssetTupleID:
      type: object
      properties:
        identifier:
          type: string
        type:
            type: string
      required:
        - identifier
        - type

    AssetReq:
      allOf:
        - $ref: '#/components/schemas/AssetTupleID'
        - type: object
          properties:
            timestamp:
              type: string
              format: date-time
            expiration:
              type: string
              format: date-time
          required:
            - expiration

    AssetResp:
      allOf:
        - $ref: '#/components/schemas/AssetTupleID'
        - type: object
          properties:
            id:
              type: integer
            first_seen:
              type: string
              format: date-time
            last_seen:
              type: string
              format: date-time
            expiration:
              type: string
              format: date-time
          required:
            - id
            - first_seen
            - last_seen
            - expiration

    # Relationships
    ParentOfReq:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        expiration:
          type: string
          format: date-time
      required:
        - expiration

    ParentOfResp:
      type: object
      properties:
        id:
          type: integer
          description: ID of the parent_of relationship.
        parent_id:
          type: integer
        child_id:
          type: integer
        first_seen:
          type: string
          format: date-time
        last_seen:
          type: string
          format: date-time
        expiration:
          type: string
          format: date-time
      required:
        - id
        - parent_id
        - child_id
        - first_seen
        - last_seen
        - expiration

    OwnsReq:
      type: object
      properties:
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      required:
        - start_time

    OwnsResp:
      type: object
      properties:
        id:
          type: integer
          description: ID of the owns relationship.
        team_id:
          type: integer
        asset_id:
          type: integer
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      required:
        - id
        - team_id
        - asset_id
        - start_time
