#!/bin/bash

set -e -u

DOCKER_COMPOSE_VERSION=1.29.2
DOCKER_COMPOSE_BIN=/usr/local/bin/docker-compose

rm -f "${DOCKER_COMPOSE_BIN}"
curl -LsS -o "${DOCKER_COMPOSE_BIN}" \
	https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
chmod +x "${DOCKER_COMPOSE_BIN}"
