#!/bin/bash

set -e -u

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

export LINTER_PATHS=${@:-'graph_asset_inventory_api tests benches'}
echo "linter paths: '${LINTER_PATHS}'"

export DOCKER_BUILDKIT=1
DOCKER_COMPOSE_PROJECT='graph-asset-inventory-api-lint'
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" build graph-asset-inventory-api-lint
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" run graph-asset-inventory-api-lint
