#!/bin/bash

# Exit on error and undefined variable.
set -e -u

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

# Run the docker-compose local environment.
DOCKER_COMPOSE_PROJECT='graph-asset-inventory-api-local'
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" build graph-asset-inventory-api-local
docker-compose -p "${DOCKER_COMPOSE_PROJECT}" run --service-ports graph-asset-inventory-api-local
