#!/bin/bash

# Exit on error and undefined variable.
set -e -u

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

# Set defaults.
GREMLIN_ENDPOINT=${GREMLIN_ENDPOINT:-'ws://gremlin-server:8182/gremlin'}
GREMLIN_AUTH_MODE=${GREMLIN_AUTH_MODE:-'none'}
DOCKER_EXTRA_HOST=${DOCKER_EXTRA_HOST:-'localhost:127.0.0.1'}
PYTEST_FLAGS=$@

echo "Gremlin endpoint: ${GREMLIN_ENDPOINT}"
echo "Gremlin auth mode: ${GREMLIN_AUTH_MODE}"
echo "Docker extra host: ${DOCKER_EXTRA_HOST}"
echo "pytest flags: '${PYTEST_FLAGS}'"

# Run the docker-compose test environment.
export GREMLIN_ENDPOINT
export GREMLIN_AUTH_MODE
export DOCKER_EXTRA_HOST
export PYTEST_FLAGS

docker-compose -f docker-compose-test.yml -p graph-asset-inventory-api-test \
	up --remove-orphans --build --exit-code-from inventory-api-test
